#!/bin/bash

NATBWMON_HOST="${NATBWMON_HOST:-192.168.0.1}"
NATBWMON_USER="${NATBWMON_USER:-root}"
SSHC="${NATBWMON_USER}@${NATBWMON_HOST}"

ssh ${SSHC} killall -q natbwmon-arm64

set -e

ssh ${SSHC} rm -f /tmp/natbwmon-arm64
GOOS=linux GOARCH=arm64 go build -o natbwmon-arm64 .
scp natbwmon-arm64 ${SSHC}:/tmp/
ssh ${SSHC} /tmp/natbwmon-arm64 \
    -nmap \
    -log.debug  \
    -aliases "7c:10:c9:3d:a9:0a=gems,00:08:9b:cf:89:4a=dubcube,38:c9:86:44:f4:3f=crangy.eth" \
    -listen "192.168.0.1:8833" \
    "${@}"
